// flow-typed signature: 0a69ccc098198a0d891cba83ed85ac24
// flow-typed version: <<STUB>>/react-photonkit_v^0.3.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-photonkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-photonkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-photonkit/dist/photon' {
  declare module.exports: any;
}

declare module 'react-photonkit/karma.config' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/dist/template-app/app' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/dist/template-app/js/menu' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/docs/assets/js/docs' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/docs/assets/js/jq' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/docs/assets/js/sticky' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/docs/dist/template-app/app' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/docs/dist/template-app/js/index' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/docs/dist/template-app/js/menu' {
  declare module.exports: any;
}

declare module 'react-photonkit/photon/Gruntfile' {
  declare module.exports: any;
}

declare module 'react-photonkit/release' {
  declare module.exports: any;
}

declare module 'react-photonkit/webpack.base.config' {
  declare module.exports: any;
}

declare module 'react-photonkit/webpack.config' {
  declare module.exports: any;
}

declare module 'react-photonkit/webpack.example.config' {
  declare module.exports: any;
}

declare module 'react-photonkit/webpack.tests.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-photonkit/dist/photon.js' {
  declare module.exports: $Exports<'react-photonkit/dist/photon'>;
}
declare module 'react-photonkit/karma.config.js' {
  declare module.exports: $Exports<'react-photonkit/karma.config'>;
}
declare module 'react-photonkit/photon/dist/template-app/app.js' {
  declare module.exports: $Exports<'react-photonkit/photon/dist/template-app/app'>;
}
declare module 'react-photonkit/photon/dist/template-app/js/menu.js' {
  declare module.exports: $Exports<'react-photonkit/photon/dist/template-app/js/menu'>;
}
declare module 'react-photonkit/photon/docs/assets/js/docs.js' {
  declare module.exports: $Exports<'react-photonkit/photon/docs/assets/js/docs'>;
}
declare module 'react-photonkit/photon/docs/assets/js/jq.js' {
  declare module.exports: $Exports<'react-photonkit/photon/docs/assets/js/jq'>;
}
declare module 'react-photonkit/photon/docs/assets/js/sticky.js' {
  declare module.exports: $Exports<'react-photonkit/photon/docs/assets/js/sticky'>;
}
declare module 'react-photonkit/photon/docs/dist/template-app/app.js' {
  declare module.exports: $Exports<'react-photonkit/photon/docs/dist/template-app/app'>;
}
declare module 'react-photonkit/photon/docs/dist/template-app/js/index.js' {
  declare module.exports: $Exports<'react-photonkit/photon/docs/dist/template-app/js/index'>;
}
declare module 'react-photonkit/photon/docs/dist/template-app/js/menu.js' {
  declare module.exports: $Exports<'react-photonkit/photon/docs/dist/template-app/js/menu'>;
}
declare module 'react-photonkit/photon/Gruntfile.js' {
  declare module.exports: $Exports<'react-photonkit/photon/Gruntfile'>;
}
declare module 'react-photonkit/release.js' {
  declare module.exports: $Exports<'react-photonkit/release'>;
}
declare module 'react-photonkit/webpack.base.config.js' {
  declare module.exports: $Exports<'react-photonkit/webpack.base.config'>;
}
declare module 'react-photonkit/webpack.config.js' {
  declare module.exports: $Exports<'react-photonkit/webpack.config'>;
}
declare module 'react-photonkit/webpack.example.config.js' {
  declare module.exports: $Exports<'react-photonkit/webpack.example.config'>;
}
declare module 'react-photonkit/webpack.tests.config.js' {
  declare module.exports: $Exports<'react-photonkit/webpack.tests.config'>;
}
