// flow-typed signature: c083459e75a61ddd28216da84ec70552
// flow-typed version: <<STUB>>/sleep_v^3.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sleep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sleep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sleep/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sleep/index' {
  declare module.exports: $Exports<'sleep'>;
}
declare module 'sleep/index.js' {
  declare module.exports: $Exports<'sleep'>;
}
declare module 'sleep/test.js' {
  declare module.exports: $Exports<'sleep/test'>;
}
