// flow-typed signature: ed83d2e67b1731d07c5ee241fe35a58d
// flow-typed version: <<STUB>>/webcamjs_vgit+https://github.com/suyashkumar/webcamjs.git/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webcamjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webcamjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webcamjs/webcam' {
  declare module.exports: any;
}

declare module 'webcamjs/webcam.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webcamjs/webcam.js' {
  declare module.exports: $Exports<'webcamjs/webcam'>;
}
declare module 'webcamjs/webcam.min.js' {
  declare module.exports: $Exports<'webcamjs/webcam.min'>;
}
