// flow-typed signature: ad721e2494491d1b31cede489709a30b
// flow-typed version: <<STUB>>/xo_v^0.9.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'xo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xo/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xo/cli.js' {
  declare module.exports: $Exports<'xo/cli'>;
}
declare module 'xo/index' {
  declare module.exports: $Exports<'xo'>;
}
declare module 'xo/index.js' {
  declare module.exports: $Exports<'xo'>;
}
